name = "foundrcheck-consumer"
main = "index.ts"
compatibility_date = "2024-11-01"

[[queues.consumers]]
queue = "IDEA_QUEUE"
max_batch_size = 10
max_batch_timeout = 5

[[d1_databases]]
binding = "DB"
database_name = "foundrcheck-db"
database_id = "REPLACE_WITH_D1_ID"

[vars]
PERPLEXITY_MODEL = "sonar-pro"
APP_TIMEZONE = "America/Los_Angeles"
RATE_LIMIT_DAILY = "3"


